=== manojramtarento/Phoenix-Zend-Propel/library/Phoenix/PDFGen/doc/relance.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT root (data, factures)>
    <!ELEMENT data (first_page, last_page)>
        <!ELEMENT first_page (contact_client, nom_client, adresse_1, adresse_2, adresse_3, code_postal,
ville, pays, lieu_relance, date_relance, num_relance, ref_relance, title, lettre_recommandee)>
            <!ELEMENT contact_client (#PCDATA) >
            <!ELEMENT nom_client (#PCDATA) >
            <!ELEMENT adresse_1 (#PCDATA) >
            <!ELEMENT adresse_2 (#PCDATA) >
            <!ELEMENT adresse_3 (#PCDATA) >
            <!ELEMENT code_postal (#PCDATA) >
            <!ELEMENT ville (#PCDATA) >
            <!ELEMENT pays (#PCDATA) >
            <!ELEMENT lieu_relance (#PCDATA) >
            <!ELEMENT date_relance (#PCDATA) >
            <!ELEMENT num_relance (#PCDATA) >
            <!ELEMENT ref_relance (#PCDATA) >
            <!ELEMENT title (#PCDATA) >
			<!ELEMENT lettre_recommandee (#PCDATA) >

        <!ELEMENT last_page (num_tva) >
            <!ELEMENT num_tva (#PCDATA) >

    <!ELEMENT factures (facture*)>
        <!ELEMENT facture (num_facture, date_facture, echeance_facture, num_ope, libelle_ope, montant_facture_total, montant_facture_restant)>
            <!ELEMENT num_facture (#PCDATA) >
            <!ELEMENT date_facture (#PCDATA) >
            <!ELEMENT echeance_facture (#PCDATA) >
            <!ELEMENT num_ope (#PCDATA) >
            <!ELEMENT libelle_ope (#PCDATA) >
            <!ELEMENT montant_facture_total (#PCDATA) >
            <!ELEMENT montant_facture_restant (#PCDATA) >

=== manojramtarento/Phoenix-Zend-Propel/library/Phoenix/PDFGen/doc/relance.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "relance.dtd">
<root>
    <data>
        <first_page>
            <contact_client>Sophie CRISTOL</contact_client>
            <nom_client>HASBRO</nom_client>
            <adresse_1>FOURNISSEURS COMPTABILITE</adresse_1>
            <adresse_2>Savoie Technolac</adresse_2>
            <adresse_3></adresse_3>
            <code_postal>73378</code_postal>
            <ville>Le Bourget du Lac</ville>
            <pays></pays>
            <lieu_relance>Rousset</lieu_relance>
			<date_relance>27/04/2011</date_relance>
            <num_relance>2</num_relance>
			<ref_relance>R2/2176</ref_relance>
			<title>Premi√®re relance</title>
			<lettre_recommandee>1</lettre_recommandee>
        </first_page>
        <last_page></last_page>
    </data>
    
    <factures>
        <facture>
            <num_facture>312137</num_facture>
            <date_facture>30/12/2003</date_facture>
            <echeance_facture>29/01/2004</echeance_facture>
            <num_ope>1717</num_ope>
            <libelle_ope>JEU BP BIENVENUE FORD FOCUS CM</libelle_ope>
            <montant_facture_total>169.39</montant_facture_total>
            <montant_facture_restant>169.39</montant_facture_restant>
        </facture>
        <facture>
            <num_facture>312137</num_facture>
            <date_facture>30/12/2003</date_facture>
            <echeance_facture>29/01/2004</echeance_facture>
            <num_ope>1717</num_ope>
            <libelle_ope>JEU BP BIENVENUE FORD FOCUS CM</libelle_ope>
            <montant_facture_total>1284.50</montant_facture_total>
            <montant_facture_restant>169.39</montant_facture_restant>
        </facture>
        <facture>
            <num_facture>312137</num_facture>
            <date_facture>30/12/2003</date_facture>
            <echeance_facture>29/01/2004</echeance_facture>
            <num_ope>1717</num_ope>
            <libelle_ope>JEU BP BIENVENUE FORD FOCUS CM</libelle_ope>
            <montant_facture_total>169.39</montant_facture_total>
            <montant_facture_restant>169.39</montant_facture_restant>
        </facture>
        <facture>
            <num_facture>312137</num_facture>
            <date_facture>30/12/2003</date_facture>
            <echeance_facture>29/01/2004</echeance_facture>
            <num_ope>1717</num_ope>
            <libelle_ope>JEU BP BIENVENUE FORD FOCUS CM</libelle_ope>
            <montant_facture_total>1284.50</montant_facture_total>
            <montant_facture_restant>500.00</montant_facture_restant>
        </facture>
        <facture>
            <num_facture>312137</num_facture>
            <date_facture>30/12/2003</date_facture>
            <echeance_facture>29/01/2004</echeance_facture>
            <num_ope>1717</num_ope>
            <libelle_ope>JEU BP BIENVENUE FORD FOCUS CM</libelle_ope>
            <montant_facture_total>169.39</montant_facture_total>
            <montant_facture_restant>0</montant_facture_restant>
        </facture>
        <facture>
            <num_facture>312137</num_facture>
            <date_facture>30/12/2003</date_facture>
            <echeance_facture>29/01/2004</echeance_facture>
            <num_ope>1717</num_ope>
            <libelle_ope>JEU BP BIENVENUE FORD FOCUS CM</libelle_ope>
            <montant_facture_total>1284.50</montant_facture_total>
            <montant_facture_restant>0</montant_facture_restant>
        </facture>
        <facture>
            <num_facture>312137</num_facture>
            <date_facture>30/12/2003</date_facture>
            <echeance_facture>29/01/2004</echeance_facture>
            <num_ope>1717</num_ope>
            <libelle_ope>JEU BP BIENVENUE FORD FOCUS CM</libelle_ope>
            <montant_facture_total>169.39</montant_facture_total>
            <montant_facture_restant>169.39</montant_facture_restant>
        </facture>
        <facture>
            <num_facture>312137</num_facture>
            <date_facture>30/12/2003</date_facture>
            <echeance_facture>29/01/2004</echeance_facture>
            <num_ope>1717</num_ope>
            <libelle_ope>JEU BP BIENVENUE FORD FOCUS CM</libelle_ope>
            <montant_facture_total>1284.50</montant_facture_total>
            <montant_facture_restant>1284.50</montant_facture_restant>
        </facture>
    </factures>
</root>
